apiVersion: apps/v1
kind: Deployment
metadata:
  name: classroom-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: classroom-service
  template:
    metadata:
      labels:
        app: classroom-service
    spec:
      containers:
      - name: classroom-service
        image: mnmustafa1109/scd-lab-final:classroom-service-39
        ports:
        - containerPort: 4235
        env:
        - name: MONGO_URL
          value: "mongodb://mongodb:27017/ClassroomMS" # Update if needed
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: classroom-service
spec:
  selector:
    app: classroom-service
  ports:
  - protocol: TCP
    port: 4001
    targetPort: 4235
