version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - shared-network
    volumes:
      - mongodb_data:/data/db

  auth-service:
    build:
      context: ./Auth
    container_name: auth-service
    ports:
      - "4000:4235"
    networks:
      - shared-network
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/ClassroomMS

  classroom-service:
    build:
      context: ./Classrooms
    container_name: classroom-service
    ports:
      - "4001:4235"
    networks:
      - shared-network
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/ClassroomMS

  post-service:
    build:
      context: ./Post
    container_name: post-service
    ports:
      - "4002:4235"
    networks:
      - shared-network
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/ClassroomMS

  event-bus:
    build:
      context: ./event-bus
    container_name: event-bus
    ports:
      - "4009:4235"
    networks:
      - shared-network

networks:
  shared-network:
    driver: bridge

volumes:
  mongodb_data:
