version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - auth-network
    volumes:
      - mongodb_data:/data/db

  auth-service:
    build: .
    container_name: auth-service
    ports:
      - "4000:4000"
    networks:
      - auth-network
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/

networks:
  auth-network:
    driver: bridge

volumes:
  mongodb_data:
